# Generated by Django 5.0.3 on 2024-03-17 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auction",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="auction",
            old_name="modified_date",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="modified_date",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="modified_date",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="modified_date",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="modified_date",
            new_name="modified_at",
        ),
    ]
